### ISSUE TITLE
add bjorn to sysadmins

### ISSUE THREAD

**Issue by berkes** [vc4all/ansible#1]
username: ?
password: ?
key: https://github.com/bjornw.keys or provide your key below.

Create a crypted password with these instructions: https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-crypted-passwords-for-the-user-module and send that to me outside of these tickets. So that I can copy that into the vault.

**Comment by BjornW** [comment]
username: bjorn
password: sent

**Comment by BjornW** [comment]
new pub key sent
